### ISSUE TITLE
Import Autodesk MAX Addon, Does not import Models Properly.

### ISSUE THREAD

**Issue by ShadyHamza** [nrgsille76/blender-io-addons#1]
Hi Sebastian,
Hope you are doing great, Thank you so much for the Max to Blender Addon, I was experimenting with it, It doesn't seem to import models Properly, I've attached a Test File below so you can test it, I'm not sure it's a version issue or what, I thought of reporting it as this addon is really beneficial to me.
[Test File.zip](https://github.com/nrgsille76/blender-io-addons/files/15411410/Test.File.zip)

**Comment by nrgsille76** [comment]
Hi Shady,
The objects matrix transformations are not applied correctly yet because they are depending on the hierarchy. By now, the mesh gets imported into world space, if you want a correct import, all transformations (location, rotation, scale) have to applied to the mesh. I am working on this problem and hope to fix it with the next update. Unfortunatly updating the files on the new blender extension platform has no proper workflow yet. I will fix the problem as soon as I can sync this repository with the extensions platform

**Comment by ShadyHamza** [comment]
Sounds great!, I really appreciate the effort, and If it's possible to share it here until the extension platform is ready, that's also would be great. Thanks :)

**Comment by nrgsille76** [comment]
@ShadyHamza I uploaded the Autodesk max addon extension to an own repository. It can now be found [here](https://github.com/nrgsille76/io_scene_max). 
Mesh transformation is fixed and hierarchy also got imported now.
Also dummy and biped objects will now be imported as empty objects
The addon has been updated and can be downloaded on [Blender Extensions](https://extensions.blender.org/add-ons/io-scene-max)

**Comment by ShadyHamza** [comment]
Thanks! The test file still doesn't seem to import correctly, do I have to check something in the settings or check boxes? same as for UVs and Material, I don't know if checking their boxes should import the meshes UVs and materials or it's intended for another purpose

**Comment by nrgsille76** [comment]
@ShadyHamza You have to check the box "apply matrix" to get the mesh transformations otherwise the mesh will be imported at point zero in world space. Materials can be imported but without texture maps, only Standard, VRay and Corona Material are supported yet. The UV meshes checkbox is for importing the UV map as mesh object. For Blender, the vertex index of the mesh and the UV map has to be the same to assign the map to the mesh. In 3ds there can be different vertex count for mesh an UVW map, I did not found a way to make this compatible. Anyone who can provide more information about the 3ds max file structure is welcome to improve the script. I only have an outdated max version to find it out and Autodesk does not provide any informations about it. The max format was also never meant to import into other platforms, if you want to import all parameters then you have to used the exchange fileformats like .3ds,  .obj or .fbx

I also tested your file in another 3D viewer wich supports max import and I got the same result as my script. I attached the screenshots.

This one is the file imported into FreeCAD
<img width="1280" alt="max_import_freecad_testfile" src="https://github.com/nrgsille76/blender-io-addons/assets/61376632/cb9c9331-1add-4c64-a1fd-52bc80fe67e8">

This one is the file imported into Blender3D
<img width="1055" alt="max_import_blender_testfile" src="https://github.com/nrgsille76/blender-io-addons/assets/61376632/bf6de519-dd81-437a-a8a2-5d2c1703cdc4">

**Comment by ShadyHamza** [comment]
[Evermotion - Archmodels vol. 252.zip](https://github.com/nrgsille76/blender-io-addons/files/15442477/Evermotion.-.Archmodels.vol.252.zip)
Totally understandable the fact that you made the conversion happen in the first place, that deserves a prize :D, Check this file out it's vray and a newer file it imports correctly, but I couldn't figure out how to import the UVmap thing, and apply the textures correctly, if you could share with me the setup or the process, it would be great.

**Comment by nrgsille76** [comment]
@ShadyHamza The imported UV meshes are usually only one square unit big if you import them, just select the meshes in outliner with the same name as the model but with .001, .002 etc and then press comma on numpad to see them. These can be used to see how the original mesh was wrapped in 3ds max but if If you want to apply textures in blender, then you have to add a new UV map and unwrap it, the image files have to be connected to the blender principled BSDF shader.
I am sure that it is possible to import the UVW maps correctly to blender but first they have to be converted into two dimensional vectors (3dsmax used a 3 dimensional vector for UVW maps, and blender only 2), then I have to find out how to reproduce the vertex index and how to merge the UVW maps into one because Blender can only have one map at one time and not multiple maps for differnt textures like 3ds max can do.

**Comment by ShadyHamza** [comment]
Oh I see, Does converting/exporting the .max file to .3ds preserve the UVs from the original max file, and converts it to 2 dimensional vector?
because i don't find issues with .3ds.. maybe when importing the .max file in blender you can make it so it converts/exchange the .max to .3ds in the background then it imports the 3ds mesh in scene with the correct UVs, like an automatic file converter.

 If I can export that file from 3dsmax as FBX or 3ds and it import correctly in blender with all the UVs and stuff, is it possible to take this exchange or export process and implement it in the addon? or maybe in a separate exchange software (non of the cloud ones work) :D, in a nut shell why not convert the .max file into a middle ground format that could preserve the attributes then imported and accepted in blender, rather than trying to import .max directly.  (sharing thoughts) i don't know I'm not a developer so don't punch me :D

**Comment by nrgsille76** [comment]
@ShadyHamza To be honest, that makes no sense^^ If you export from 3ds max to fbx, obj or 3ds then all parameters and values get converted to the fbx, obj and 3ds specifications and they can then be imported to blender with the fbx, obj or 3ds importer directy and you won't need this script. The .max format is how 3ds max stores all data like blender does with a .blend file and there is no .blend importer on the other side because thats what the conversion file formats fbx, obj and 3ds are made for.
I also have written the .3ds script and it works properly because I got enough information about the file format. 3ds is a complete binary file and Autodesk 3ds max stopped supporting it in 2001 thats why it got no changes since then. The latest Autodesk 3ds max versions can not even import and export as many features as the Blender addon can do now.

**Comment by ShadyHamza** [comment]
I mean if you can convert the .max to FBX/OBJ in an automated process, before importing it in blender that could fix the issue, as if you take the .max then converting it to OBJ or FBX in a cloud service or different software like FreeCad then importing it in blender, but instead the process of converting is done internally in the addon

**Comment by ShadyHamza** [comment]
you are correct if i have 3dsmax in the first place to convert the files, but if i don't have it, ill need an exchange software or plugin to convert the .max to any other format

**Comment by nrgsille76** [comment]
@ShadyHamza This addon uses the same process like the FreeCAD plugin, it would not make any difference to take the roundabout over obj or fbx and other convertes will always loose data. I do not know any converter or cloud service wich has proper results, thats the reason why I made this script

**Comment by ShadyHamza** [comment]
so If i opened the file in 3dsmax then exported it as fbx, it will import in blender with fixed UVs or still not?

**Comment by ShadyHamza** [comment]
never mind, this should be paid addon bro :D it will kill it in blender market

**Comment by nrgsille76** [comment]
@ShadyHamza  Yea if you export from 3dsmax to fbx, everthing should be okay.
The next update of this addon will have the UVs fixed, I already figured it out for most of the files.
Some files still got issues especially if there a mixed polygons (mixed tris, quads and ngons)

**Comment by ShadyHamza** [comment]
You're a life saver :D, I really appreciate your effort!

**Comment by ShadyHamza** [comment]
[Vray.zip](https://github.com/nrgsille76/blender-io-addons/files/15450343/Vray.zip)
Hey, the UVs seems to work great!, but the some meshes are missing when imported in this test file

**Comment by ShadyHamza** [comment]
the previous release imported everything
